// Versiones inmutables: los cambios futuros se agregan como nuevas migraciones.
export const migrations = [
  {
    name: '001-baseline',
    sql: [
      `CREATE TABLE IF NOT EXISTS CUENTAS (ID_CUENTA INTEGER PRIMARY KEY AUTOINCREMENT, KEYCLOAK_SUB VARCHAR(120) NOT NULL UNIQUE, USERNAME VARCHAR(100) NOT NULL, EMAIL VARCHAR(150))`,
      `CREATE TABLE IF NOT EXISTS LISTAS (ID_LISTA INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRE VARCHAR(100) NOT NULL, ID_CUENTA INTEGER NOT NULL REFERENCES CUENTAS(ID_CUENTA) ON DELETE CASCADE ON UPDATE CASCADE, DESCRIPCION VARCHAR(250), COLOR VARCHAR(30), FECHA_CREACION DATETIME NOT NULL)`,
      `CREATE UNIQUE INDEX IF NOT EXISTS UK_listas_cuenta_nombre ON LISTAS(ID_CUENTA, NOMBRE)`,
      `CREATE TABLE IF NOT EXISTS TAREAS (ID_TAREA INTEGER PRIMARY KEY AUTOINCREMENT, TITULO VARCHAR(150) NOT NULL, DESCRIPCION VARCHAR(500), COMPLETADA TINYINT(1) NOT NULL DEFAULT 0, PRIORIDAD VARCHAR(10) NOT NULL DEFAULT 'media', FECHA_VENCIMIENTO DATE, FECHA_CREACION DATETIME NOT NULL, ETIQUETAS TEXT, ID_LISTA INTEGER NOT NULL REFERENCES LISTAS(ID_LISTA) ON DELETE NO ACTION ON UPDATE CASCADE)`,
    ],
  },
  {
    name: '002-collection-indexes',
    sql: [
      'CREATE INDEX IF NOT EXISTS IX_tareas_lista_fecha_id ON TAREAS(ID_LISTA, FECHA_CREACION, ID_TAREA)',
      'CREATE INDEX IF NOT EXISTS IX_tareas_lista_completada ON TAREAS(ID_LISTA, COMPLETADA)',
    ],
  },
] as const;
